### PR TITLE
[WIP] Feature/key to id mapping

### PR DESCRIPTION
**Pull request by leevigraham**
Hey @rsanchez,

I cleaned up the key to id transformer code by adding a new AbstractCommand class, a `transformKeyToId($key, $value)` method. 

I have run a couple of tests but nothing extensive. Throwing this up for any feedback / thoughts.

### CODE REVIEW

**Comment by rsanchez** [comment]
Haven't had a chance to look yet, but I will when I have time.

**Comment by leevigraham** [comment]
Rebased this with the latest changes. Any feedback?

**Comment by rsanchez** [comment]
It’s been on my todo list…for a while :/ Sorry about that.

It’s such a large patch that I haven’t had time to review it yet. My initial reaction is that I still might prefer to build the mapping into each command itself, rather than having a global transform method.

**Comment by leevigraham** [comment]
> My initial reaction is that I still might prefer to build the mapping into each command itself, rather than having a global transform method.

Yeah that's a fair call. The only issue I can see with breaking it out into each command is that some commands might need multiple transforms for related data. Example channels need category_group and field_group while category also needs category_group. This would lead to lots of duplication.

Maybe traits could solve this?

**Comment by leevigraham** [comment]
I've also added a CreateImageManipulationCommand command to this PR. It doesn't use the controller style you've used in other commands as I would have needed to add all the upload pref information to the post. This is a straight DB insert.

**Comment by rsanchez** [comment]
Do you want to submit CreateImageManipulationCommand as a separate pull?

I have no problem with not using a controller when it's not needed.

**Comment by leevigraham** [comment]
bq. Do you want to submit CreateImageManipulationCommand as a separate pull?

Yep I can split it out. I'll do that today.

**Comment by leevigraham** [comment]
The only reason why I added it to this PR was because of transformKeyToID method: https://github.com/rsanchez/eecli/pull/14/files#diff-a6280b33330f0ce095ff463dcbb6b80bR86

**Pull request closed without merging**
